import type { occupationsShape } from "./interfaces";

 const occupations = [
  { name: "Data Courier", district: 12 },
  { name: "Ration Clerk", district: 1 },
  { name: "Grid Technician", district: 3 },
  { name: "Synth-Meat Vendor", district: 6 },
  { name: "Checkpoint Guard", district: 2 },
  { name: "Air Filtration Engineer", district: 3 },
  { name: "Street Medic", district: 10 },
  { name: "Signal Jammer Repairman", district: 12 },
  { name: "Municipal Archivist", district: 1 },
  { name: "Drone Pilot", district: 12 },
  { name: "Curfew Enforcer", district: 2 },
  { name: "Black Market Trader", district: 7 },
  { name: "Power Relay Operator", district: 3 },
  { name: "Facial Scan Technician", district: 12 },
  { name: "Housing Inspector", district: 5 },
  { name: "Pipe Welder", district: 3 },
  { name: "Noodle Stall Cook", district: 9 },
  { name: "Freight Loader", district: 11 },
  { name: "Surveillance Analyst", district: 2 },
  { name: "Print Forger", district: 7 },
  { name: "Tenement Landlord", district: 5 },
  { name: "Water Ration Auditor", district: 4 },
  { name: "Neon Sign Installer", district: 8 },
  { name: "Pawnbroker", district: 7 },
  { name: "Transit Conductor", district: 11 },
  { name: "Chem Lab Assistant", district: 3 },
  { name: "Registry Clerk", district: 1 },
  { name: "Vagrant Processor", district: 2 },
  { name: "Scrap Metal Dealer", district: 7 },
  { name: "Vaccine Runner", district: 10 },
  { name: "Pest Control Operative", district: 3 },
  { name: "Hydroponics Farmer", district: 13 },
  { name: "Municipal Debt Collector", district: 5 },
  { name: "Elevator Mechanic", district: 11 },
  { name: "Border Interpreter", district: 1 },
  { name: "Undercover Informant", district: 2 },
  { name: "Antenna Rigger", district: 12 },
  { name: "Ration Card Printer", district: 1 },
  { name: "Alley Vendor", district: 6 },
  { name: "Cybernetics Fitter", district: 3 },
  { name: "Broadcast Censor", district: 12 },
  { name: "Sewage Technician", district: 4 },
  { name: "Loyalty Auditor", district: 1 },
  { name: "Textile Weaver", district: 3 },
  { name: "Streetlamp Repairer", district: 5 },
  { name: "Contraband Sniffer", district: 2 },
  { name: "Records Clerk", district: 1 },
  { name: "Prosthetics Technician", district: 10 },
  { name: "Wastewater Recycler", district: 4 },
  { name: "Fingerprint Analyst", district: 1 },
  { name: "Bunker Custodian", district: 2 },
  { name: "Cargo Inspector", district: 11 },
  { name: "Firmware Cracker", district: 3 },
  { name: "Propaganda Illustrator", district: 12 },
  { name: "Currency Exchanger", district: 6 },
  { name: "Skyline Window Cleaner", district: 5 },
  { name: "Detention Clerk", district: 2 },
  { name: "Vending Machine Restocker", district: 6 },
  { name: "Reactor Janitor", district: 3 },
  { name: "ID Verification Officer", district: 1 },
  { name: "Smuggler's Contact", district: 7 },
  { name: "Rooftop Farmer", district: 13 },
  { name: "Cable Splicer", district: 3 },
  { name: "Traffic Signal Operator", district: 11 },
  { name: "Barcode Tattooist", district: 8 },
  { name: "Riot Cleanup Crew", district: 2 },
  { name: "Meat Ration Butcher", district: 9 },
  { name: "Alley Locksmith", district: 7 },
  { name: "Municipal Herbalist", district: 10 },
  { name: "Terminal Operator", district: 11 },
  { name: "Freight Dock Foreman", district: 11 },
  { name: "Radiation Sweeper", district: 13 },
  { name: "Interrogation Clerk", district: 2 },
  { name: "Fabric Dyer", district: 3 },
  { name: "Cold Storage Attendant", district: 11 },
  { name: "Chip Implant Technician", district: 3 },
  { name: "Underpass Beggar", district: 13 },
  { name: "District Announcer", district: 1 },
  { name: "Loudspeaker Repairman", district: 12 },
  { name: "Night Shift Welder", district: 3 },
  { name: "Ration Line Marshal", district: 1 },
  { name: "Synth Fuel Attendant", district: 3 },
  { name: "Rooftop Pigeon Keeper", district: 13 },
  { name: "Alleyway Fortune Teller", district: 8 },
  { name: "Salvage Diver", district: 11 },
  { name: "Municipal Tailor", district: 6 },
  { name: "Compound Interest Broker", district: 7 },
  { name: "Checkpoint Translator", district: 1 },
  { name: "Vent Shaft Cleaner", district: 4 },
  { name: "Battery Reclaimer", district: 3 },
  { name: "District Cartographer", district: 1 },
  { name: "Bootlegger", district: 7 },
  { name: "Signal Tower Climber", district: 12 },
  { name: "Ash Filter Changer", district: 13 },
  { name: "Municipal Barber", district: 6 },
  { name: "Quarantine Officer", district: 10 },
  { name: "Freight Train Brakeman", district: 11 },
  { name: "Neon Bulb Trader", district: 6 },
  { name: "Alley Cook", district: 9 },
  { name: "Detention Camp Cook", district: 2 },
  { name: "Waste Sorter", district: 13 },
  { name: "Grid Maintenance Supervisor", district: 3 },
];

function shufflejobs(a: occupationsShape[]) {
    for (let i = a.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [a[i], a[j]] = [a[j], a[i]];
    }
  }

export function CreateOccupation(){
    shufflejobs(occupations)
    return occupations[0]

}